image: node:latest

cache:
  paths:
    - ./node_modules/

stages:          # List of stages for jobs, and their order of execution
  - build

staticpages:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - mv out staticpages
  artifacts:
    paths:
      - staticpages
