image: node:latest

cache:
  paths:
    - draft/langat-website/node_modules/

stages:          # List of stages for jobs, and their order of execution
  - build

pages:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    - npm run build
    - cp -a dist public
  artifacts:
    paths:
      - public
