image: node:latest

cache:
  paths:
    - ./node_modules/

stages: # List of stages for jobs, and their order of execution
  - build

pages: # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - rm -rf public
    - mv out public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
